### PR TITLE
eng-rus

### PR DESCRIPTION
**Pull request by axet**
More words.

Please check my work, if it done right.

1) Some words has duplicate entries like "hide" for "verb" and "noun" variants.

2) Some empty <cit> because here is no translation for "the", with only 'hint' attribute filled.

3) Some has several translation, several cit tags.

Also I'm using gramGrp in may ways: preposition, conjunction, noun, adjective, adverb, numeral.

### CODE REVIEW

**Comment by humenda** [comment]
Thanks for the2nd batch. I would ask you for a bit of patience, I'll look into
it in the next few days.

**Comment by humenda** [comment]
I would like to see the grammar info to be slightly changed:

```
+        <gramGrp>
+          <pos expand="preposition">p</pos>
+        </gramGrp>
```

Could you make it more in line with other dictionaries, i.e. without the
attribute and with a more common abbreviation?

```
        <gramGrp>
          <pos>prep</pos>
        </gramGrp>
```

You should have a look at the WikDict dictionaries
(https://freedict.org/download) and see how POS'es are handled there.

**Comment by humenda** [comment]
>1) Some words has duplicate entries like &quot;hide&quot; for &quot;verb&quot; and &quot;noun&quot; variants.

I don't speak Russian. What exactly is your question?

>2) Some empty &lt;cit&gt; because here is no translation for &quot;the&quot;, with only &#39;hint&#39; attribute filled.

Have you tried building the dictionary, i.e. `make build-dictd` and look at
build/dictd/eng-rus.c5? It looks ok to me and it validates, so should be fine.
It is best to ask this on the mailing list
<https://www.freelists.org/list/freedict>.

>3) Some has several translation, several cit tags.

That is correct like tis.

>Also I&#39;m using gramGrp in may ways: preposition, conjunction, noun, adjective, adverb, numeral.

Please check out the WikDict dictionaries (see https://freedict.org/download).
Those have a common ontology, i.e. a common tagging of "part-of-speech POS".
Typical are prep, int, adj, adv, n (like noun/nomen), v (like verb), part
(like particle).

Could you do these small changes and squash your commits into one? Thanks

**Comment by axet** [comment]
1) Here is nothing to do with Russian. "hide someone in a shelf" or "hide of an animal" can be translated differently. It called "homonym". How should I handle that in xml? I made two separate independent entries for "hide" word.

2) Ok. Not sure if only one tag "hint" for untranslated words would work with GoldenDict (and other dicts apps) or not. That was the question. I guess we will see. But common case, I did hope it had answer already.

3) Sure I will update grammar and squish it.. But I do not see WikiDict on link you provided. Can you be more specific what grams should I use and where to read about it? (https://freedict.org/downloads/ the correct link)

Does "int" stands for interjection? What should I use for "numeral" and "determiner"?

**Comment by humenda** [comment]
>1) Here is nothing to do with Russian. "hide someone in a shelf" or "hide of an animal" can be translated differently. It called "homonym". How should I handle that in xml? I made two separate independent entries for "hide" word.

Yes, make them separate entries. The `<mom/>` tag is not supported.

>2) Ok. Not sure if only one tag "hint" for untranslated words would work with GoldenDict (and other dicts apps) or not. That was the question. I guess we will see. But common case, I did hope it had answer already.

Please ask your question on the list, I don't have the time to answer
everything on my own and it seems that most people are not following GitHub
along :-(. Could you provide an example entry for your question? This would help me to understand your question.

However, the question boils down to which format you intend to use. If you use
slob, the story is different comparing to the dict format, as both use
different converters.  But let's discuss this somewhere ele, not on this PR
:).

>3) Sure I will update grammar and squish it.. But I do not see WikiDict on link you provided. Can you be more specific what grams should I use and where to read about it? (https://freedict.org/downloads/ the correct link)

You are right, it doesn't advertise them as WikDict dictionaries. Select for
instance Dutch-Russian, that's a WikDict dictionary.

>Does "int" stands for interjection? What should I use for "numeral" and "determiner"?

Yes, interjection. Numeral is num and the full list is in our HOWTO that you
should check out to learn about different word encodings:

https://github-wiki-see.page/m/freedict/fd-dictionaries/wiki/FreeDict-HOWTO-%E2%80%93-Writing-A-FreeDict-Dictionary

Thanks

**Comment by bansp** [comment]
Maybe it's time to protect the master branch? And go via pull requests?

**Comment by bansp** [comment]
Ah, this _was_ a pull request, but I'm lost as to why the author was able to go through with it himself, by force :-)

**Comment by axet** [comment]
After 2 idle months 'author' forgot that his master branch was pointing to origin of freedict/fd-dictionaries... properly rebased changes and force pushed the branch, as rebase suppose to work... Question is who have the recent master, if here were commits in the past two months...

**Comment by humenda** [comment]
What do you mean by recent commits and "having master"? There has not been any
development on fd-dictionaries recently. Part of the reason is that we don't
have much manual dictionary editing currently, but mostly auto-generated
dictionaries that are not tracked in Git. I will take a look at your MR at the
weekend.

**Pull request closed without merging**
