### PR TITLE
eng-deu: corrections

### PR DESCRIPTION
**Pull request by ivan-pan**
I corrected some mistakes such as _Aufenhalt_.

### CODE REVIEW

**Comment by humenda** [comment]
Hi

Thank you for looking into eng-deu.
I could merge your PR, but unfortunately your corrections are based on outdated
data. Eng-deu and deu-eng are imported from
https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en-devel/ and we act as a
distributor here. Is there any chance you would like to take up writing an
importer script? Our dictionary versions are from 2005
and unfortunately, the scripts to import the format into TEI XML are lost.
Besides, the format grew much more complex over time and we need a new parser
anyway.

I am sorry for the unecessary work that you have invested, but we should not
maintain a fork from the TU Chemnitz data. Instead we would really appreciate
help here.

**Comment by humenda** [comment]
If you were to write a new importer/converter from the DING to the FreeDict TEI
P5 XML format, I could merge your changes for the meantime to see at least some
improvements before the new version arrives. This depends on you.

**Comment by ivan-pan** [comment]
All right, thanks for making me aware of the ding word list; I suggested some corrections to BEOLINGUS in the past but did not know of a downloadable database. I am currently not planning to write an importer script.

**Comment by humenda** [comment]
I will see whether I'll find some time in the near future. It'd be good to have
it imported again to avoid double dictionary development effort.

**Comment by Bushmills** [comment]
There's nothing wrong with some words you've changed, like Glühkathode or Hinterwäldler.
I didn't look at all changes, but my impression is that the changes need to be reviewed prior to incorporating them into the dictionary.

**Comment by ivan-pan** [comment]
@Bushmills, I actually changed _Glühkatode_ to _Glühkathode_ and later realized that both spellings are acceptable, which is why I changed back to the spelling that was originally there (i.e., _Glühkatode_). Also, I already reverted my change of _Hinterwäldler_ on 2 September 2019.

**Comment by humenda** [comment]
@ivan-pan Actually, there's work ongoing regarding the importer, see
https://github.com/freedict/tools/tree/ding2tei-haskell-rewrite . So please
take the opportunity and report your improvements for **this particular**
dictionary to the DING folks; I posted the link already. For all of the other
dictionaries, we of course do appreciate PRs. This one is however a bit
special. Sorry about the confusion.

**Pull request closed without merging**
