### PR TITLE
eng-spa: beget: Add word

### PR DESCRIPTION
**Pull request by alejandro-colomar**
I don't know the pronounciation

### CODE REVIEW

**Comment by humenda** [comment]
Thanks for your work. However, maintaining a dictionaries is usually a bit
more effort. If you would like to help out, I would ask you to add more words
at once, to keep the amount of PRs manageable.

**Comment by humenda** [comment]
And it would help if all your previous changes were merged into one PR :).
Thanks

**Comment by humenda** [comment]
Unfortunately, there has not been any reaction so far. I'm closing the PR hence,
but would be happy to resume working on it (see comments above).

**Comment by alejandro-colomar** [comment]
Sorry, I have it in my queue.  I'll try to find some time for it.  :)

**Comment by humenda** [comment]
For larger dictionaries or those which have a maintainer, we like to keep
"our" version. engp-spa and spa-eng are unfortunately really small and haven't
seen much attention for long. I would therefore even go and replace it with
the auto-imported WikDict, i.e. Wiktionary, version. Any thoughts?

**Comment by alejandro-colomar** [comment]
> For larger dictionaries or those which have a maintainer, we like to keep "our" version. engp-spa and spa-eng are unfortunately really small and haven't seen much attention for long. I would therefore even go and replace it with the auto-imported WikDict, i.e. Wiktionary, version. Any thoughts?

I've only started using the dictionary recently, and since I don't encounter new words that I don't know how to translate from English to Spanish, I don't use it very often, so I don't have a strong opinion.  If it makes sense to you, it's probably a reasonable idea.

**Pull request closed without merging**
