### PR TITLE
add dawn word

### PR DESCRIPTION
**Pull request by axet**

### CODE REVIEW

**Comment by humenda** [comment]
Hi

thanks for your contribution. Is there a chance you would like to work on
eng-rus more regularly, i.e. become a maintainer?

**Comment by axet** [comment]
Since here almost no pull requests. I could help you review the content. Just CC me when you need.

**Comment by humenda** [comment]
Ok. It is just that if you are going to add more words on a regular basis, it
would be much easier if you commit yourself.

**Comment by axet** [comment]
Sure, I can update eng-run repo directly.

**Pull request merged**
